# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи перестановки та символ Леві-Чивіти.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [17]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix


def list_matrix_n(dim):
    '''створює список, в якому елементи є перестановки (n!, де n - порядок матриці)'''
    lst = []
    for i in range(1, dim+1):
        lst.append(str(i))
    string = ''.join(lst)
    t = list(itertools.permutations(string, dim))
    return t


def matrix(dim):
    n = dim
    matrix = []
    for i in range(n):
        print('Введіть через пробіл елементи рядка матриці №', i+1)
        append = (input('Введіть '))
        if len(append)- n + 1 != n:
            print('Елементів в рядку повино бути:', n)
            continue
        else:
            matrix.append(append)
    for k in range(n):
        matrix[k] = matrix[k].split()
    for k in range(n):
        for i in matrix[k]:
            i = float(i)
    return matrix




def calcute_det(t, dim):
    '''за допомогою цієі функції створюється список добутків елементів з правильним знаком,
    (число Леві-Чивіти)'''
    matrix = random_matrix(dim)
    print(matrix)
    matrix_lst = []
    for i in matrix:
        i = str(i)
        i = i.replace('[', '').replace(']', '')
        i = i.split(' ')
        i = list(i)
        matrix_lst.append(i)
    t_lst = []
    for i in t:
        i = str(i)
        i = i.replace('[', '').replace(']', '').replace("'", "").replace('(', '').replace(')', '').replace(',', '')
        i = i.split(' ')
        i = list(i)
        t_lst.append(i)
    lst_c = []
    for i in t_lst:
        e = 0
        c = 1
        for k in range(len(i)):
            for n in range(k):
                if int(i[n]) > int(i[k]):
                    e = e + 1
            i[k] = int(i[k])
            j = i[k]
            c = c * float(matrix_lst[k][j-1])
        if e%2 != 1:
            lst_c.append(c)
        else:
            c = -1*c
            lst_c.append(c)
    return lst_c





def calcute_det_2(t, dim):
    '''за допомогою цієі функції створюється список добутків елементів з правильним знаком,
    (число Леві-Чивіти)'''
    mat = matrix(dim)

    print(mat)
    t_lst = []
    for i in t:
        i = str(i)
        i = i.replace('[', '').replace(']', '').replace("'", "").replace('(', '').replace(')', '').replace(',', '')
        i = i.split(' ')
        i = list(i)
        t_lst.append(i)
    lst_c = []
    for i in t_lst:
        e = 0
        c = 1
        for k in range(len(i)):
            for n in range(k):
                if int(i[n]) > int(i[k]):
                    e = e + 1
            i[k] = int(i[k])
            j = i[k]
            c = c * float(mat[k][j-1])
        if e%2 != 1:
            lst_c.append(c)
        else:
            c = -1*c
            lst_c.append(c)
    return lst_c





def results(dim):
    '''
    Функція, що виводить на екран суму добутків елементів матриці
    '''
    print('Випадкова матриця порядку', dim)
    s = 0
    t = list_matrix_n(dim)


    for i in calcute_det(t, dim):
        s = s + float(i)
    print('Визначник матриці:', s)

def results_2(dim):
    s = 0

    t = list_matrix_n(dim)
    for i in calcute_det_2(t, dim):
        s = s + float(i)
    print('Визначник матриці:', s)

def vibor(dim):
    v = input('Чи бажаєте ви самостійно ввести матрицю? (Y - так, будь-яка інша клавіша - ні) ')
    if v == 'Y' or v == 'y':
        results_2(dim)
    else:
        results(dim)


try:
    dim = int(input('Введіть порядок матриці: '))

    if dim < 1:
        raise ValueError('Вводити треба тільки цілі додатні числа!')
    else:
        vibor(dim)
except:
    print('Вводити треба тільки цілі додатні числа!')



Випадкова матриця порядку 3
[[4 4 7]
 [0 2 9]
 [3 3 0]]
Визначник матриці: -42.0
